package com.nokinori.reactive.rabbitmq.props

import java.time.Duration

/**
 * Useful class that can be used for consumer properties.
 */
data class EventConsumerConfiguration(
    /**
     * Queue name. If not specified it would be generated by `prefix.routig-key`.
     * @see [com.nokinori.reactive.rabbitmq.queueName]
     */
    val routingKey: String,
    val queue: String? = null,
    val durableQueue: Boolean = true,
    val maxRetry: Int = 3,
    val retryDelay: Duration = Duration.ofMinutes(1)
)